name: CI

on: [push, pull_request]

jobs:
  racket-package-ci:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: jackfirth/racket-package-ci-action@v0.1.4
      with:
        name: rebellion
